---

- name: Deploy application
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/{{ deploy_user }}/reddit'
        version: monolith
      become: yes
      become_user: '{{ deploy_user }}'
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: '/home/{{ deploy_user }}/reddit'
  handlers:
    - name: reload puma
      become: yes
      systemd:
        name: puma
        state: restarted
