#cloud-config

package_update: true
package_upgrade: true

users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbRbxUBq5zT8RVXa85uw19ReqQqU2xiRH8I5fLAi83xPL7CievatKZFdIQ2yp+A6ezrgfzdfQEkONc9KfzFvYcRSWWmM+cA+Nns+scLLdN6VMQ0RjFp2+SRZapO7GNP2deU3C59lnAtdMTwRDNsmm2jaiD/FbZckfhq4XPiivbrVV/Bq/peFmj9AYOqj9UW8GQTylIQs3NwkDhxVLvJZPYmnm5uG39qwzbgJTWpO2ug3nv4+rCnGa8SHibgnt2jh+0wcKu7d+3rQ1nsVTlNUxjpSkkUkgI91skHxgK0UqwPvT8M89SPSqRVrRjtzUaL/dlY9Xva1DWVvSkNAjgt3Z5uo6DjIGO/wG/8mdGPuccgaIEmkLPik4e8+0SqIpdGHo45lq14+xPES6SF70zAGxnPkMHM00lxuGXJJAyu8HfvOf8b0yUNvv+si/S2YO+EEkubCEq7uZN2sbSMz4KgJyGrJlBViQ4mmdnb8XsQgwkpjunc/baWUacnbQSpeRQAoc= kostin@MBP-Aleksej'

apt:
  preserve_sources_list: true
  sources:
    mongodb-org-4.2.list:
      source: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
      filename: mongodb-org-4.2.list
      key: | # The value needs to start with -----BEGIN PGP PUBLIC KEY BLOCK-----
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1.4.11 (GNU/Linux)

        mQINBFrXrqYBEACscLj2qgPpHBCQtgW1Yh29Ddgv6jssyWLAYmj0qngFLKoQMMbt
        SNBZylIKxfS+pUD9J5xfRZwfZOmtMIOFVWS9tcpeQXsiwC126tRyoFCIpoTmH7+R
        8/FfPrCYyXLP+ftEZfRV60wTwr5drR0S5pVIST3oaXXGkHkFC35U++udUG2Tl4Cs
        OPSCp1tsK6UOTjHFDH8PnasImJgD37QC8OOMIJS0jCtDZywJW6OCdpIRbuTWPK3P
        P48NLwGUJHixhVCmOgPPu9kDAfG3wLxiN85S2UbaaSXsdA4fF4SSwWNHTIYAg0yT
        xGepVyW4lkfcvng4jva24rQ9j1cm1b7bWeOkMH1aAcSyFzKCeNCNxbVOYVrcWNP4
        zrSUvsTKhwX8rPFMq9LkcKirDL9bRILvn/24VU6NdJfGbRjR6+Q7ooj7hYKLXtO5
        q0Q4nhjigpTWIoU6jdfbM9YqpKSELNnkDRAU+bRYSrNaFuizYgDZQvcVT6gbq26f
        JbgihoeJogEfim3kqRRJ3EUhE+EaVijl9iLDKkpurod26P2QSq9RKSuOCeauPjQv
        3BIiEMXco8O3v8W1y4TbnSQ3d28W9pN28IgAhmN2EU2sKqWPzNeG0V+L6mE5pA4o
        nD3z3JRpxAUFw08+9LnLRZ4D1u54OrHADsU8UpYZJCm1xw6T0e4dlxW6rQARAQAB
        tDdNb25nb0RCIDQuMiBSZWxlYXNlIFNpZ25pbmcgS2V5IDxwYWNrYWdpbmdAbW9u
        Z29kYi5jb20+iQI+BBMBAgAoBQJa166mAhsDBQkJZgGABgsJCAcDAgYVCAIJCgsE
        FgIDAQIeAQIXgAAKCRBLfFSaBY+LaxdXEACJMvkgr3Nt2xme9/6brGMbrEy6mQn7
        DZP98DXuS0tWvO5vkEO5IfRIvzG3zA0pATSBDVA0BvGnebQrGXZZ7Xfh0gz+zxlt
        TXv4eCyb6T4gRJuuQSFPTyDnZ3MbPESqj0UpIALmcLDJ01nqvbNPKxx5r08XQOtE
        i44Kcwc1Px5cPcYP9nmpDNLZjz3gkTm+zBygdE9beP02qXq7WcyghFmQZoLBW53e
        TqNPnMrrm5+6vgq+r/ttyiYTo7Zw8MrifN5okevzB0JhhSAW9g+4ZOp1QYbV8u8V
        pksJQDOIaBWIw8zosIQJTCVyd4hOyl8Ib2s2R0/grT51RgLYCNbUG6WTpKGgYBtr
        Mng10gozyDrnA3B+RiDx5uq+dNzuuMXWMit2nbcdanXdKNkaPmC6WVeU0rG5K1Wz
        jQMDvAInTszLcqH6zfEsjCoXj0z8UwcC4jahFDNMDBk3OhjMSL+fnvIhW84nKVHf
        AWL5jjSQdkrM/M8QRpRqls5apuIYHQwo6Oyd2Nk0n9T/GOMJ1jilxiPw9ihusf+k
        DfU0JI7T8fgxIv/wHNXUg7FOaaDJIfgGlCPUgtsNUDZZ9lFq+Zc5H8Wff3LNo7Se
        2xnzzoy2e+C3tsxAmVUTs+q0lyIzEK24lf71cp074KVV7rIYBELYtO2hAlJYjXJU
        bscTTjCKLf9leA==
        =UXPP
        -----END PGP PUBLIC KEY BLOCK-----

packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - mongodb-org
  - git

runcmd:
  - [ systemctl, start, mongod ]
  - [ systemctl, enable, mongod ]
  - [ mkdir, "/srv/app" ]
  - [ git, clone, '-b', monolith, "https://github.com/express42/reddit.git", /srv/app ]
  - cd /srv/app && bundle install && puma -d
