---
- name: Configure App
  hosts: app
  tags: app-tag
  become: yes
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
    - name: Add config for DB connection
      template:
        src: templates/db.env.j2
        dest: /home/ubuntu/db.env
        owner: ubuntu
        group: ubuntu
    - name: enable puma
      systemd:
        name: puma
        enabled: yes
        daemon_reload: yes
